---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: loadtest
  # namespace: http
  labels:
    k8s-app: loadtest
    ref: ref-loadtest
    track: loadtest
spec:
  replicas: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      k8s-app: loadtest
      ref: ref-loadtest
      track: loadtest
  template:
    metadata:
      labels:
        k8s-app: loadtest
        ref: ref-loadtest
        track: loadtest
    spec:
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
      - image: dolphyvn/loadtest
        name: loadtest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
        env:
          - name: TEST_SITE
            value: "ftp://ftp.ega.ebi.ac.uk"
        resources:
          limits:
            cpu: 400m
            memory: 1024Mi
          requests:
            cpu: 400m
            memory: 1024Mi
        volumeMounts:
        - name: tmp-script
          subPath: load-test.sh
          mountPath: /tmp/load-test.sh
      volumes:
      - name: tmp-script
        configMap:
          name: tmp-script

